Repository MDS-grupo-9/MDS_Project, pull requests merged in 2023-05, with the labels that each got.

#27 Criação de novos documentos
  CODE_OF_CONDUCT.md
  Documentação/branches.md
  Documentação/commits.md
  Documentação/documento-de-visao.md
Labels: documentação

#32 :bulb: (#17): Criando issue template
  .github/ISSUE_TEMPLATE/custom.md
Labels: organização

#33 🔁 #30 documento-de-arquitetura.md
  documento-de-arquitetura.md
Labels: documentação

#35 :repeat: (#30): Renomeando o diretório
  docs/bancoDados.html
  docs/images/foto_exemplo.jpg
  docs/images/foto_prof.jpg
  docs/images/fundo_unb.png
  docs/images/unb_logo.jpg
  docs/index.html
  docs/professores.html
  docs/quemSomos.html
  docs/readme.md
  docs/styles/CSSReset.css
  docs/styles/bancoDados.css
  docs/styles/index.css
  docs/styles/professores.css
  docs/styles/quemSomos.css
  docs/styles/styles.css
Labels: organização

#37 Documentation/novos documentos 2/sprint02
  Documentação/Documentação
  Documentação/Documentação do frontend.md
  Documentação/atas/ata-sprint-03.md
  Documentação/atas/ata-sprint01.md
  Documentação/documento-de-visao.md
  Documentação/roadmap.md
  Documentação/termo-de-abertura-do-projeto.md
  README.md
  documento-de-arquitetura.md
Labels: documentação, organização

#49 :pencil: (#38): Adicionando políticas de contribuição
  CONTRIBUTING.md
Labels: documentação

#50 Documentation/revisao de documentos/sprint03
  Arquitetura.jpg
  Documentação/Backlog do projeto.txt
  Documentação/Backlog.md
  Documentação/CODE_OF_CONDUCT.md
  Documentação/documento-de-arquitetura.md
Labels: documentação

#48 🔁 (#36): README.md
  README.md
Labels: documentação, organização
